### ISSUE TITLE
loading deprecation warning

### ISSUE THREAD

**Issue by kvanwerkhoven** [RTIInternational/teehr#117]
```
/srv/conda/envs/notebook/lib/python3.10/site-packages/teehr/loading/nwm/point_utils.py:40: FutureWarning: 'H' is deprecated and will be removed in a future version. Please use 'h' instead of 'H'.
  + pd.to_timedelta(int(row.z_hour[1:3]), unit="H")
```

warning repeated 100s-1000s of times as loading runs

**Comment by samlamont** [comment]
Looks like a versioning issue, TEEHRHub is running pandas version 2.2.0 while version 2.1.3 is specified in the poetry lock file.

**Comment by kvanwerkhoven** [comment]
Can this be addressed?  These warnings are really bogging down the loading, something typically taking a few min did not complete overnight.

**Comment by mgdenno** [comment]
You should be able to suppress the warning with this:

`warnings.filterwarnings("ignore", category=FutureWarning, module='pandas')`

**Comment by samlamont** [comment]
@kvanwerkhoven I am working on addressing this now.
