### ISSUE TITLE
Explore NWM retrospective gridded analysis on MERIT basins

### ISSUE THREAD

**Issue by samlamont** [RTIInternational/teehr#124]
* Test feasibility of using TEEHR to calculate MAP for CONUS-wide MERIT basins on NWM v3.0 retrospective AORC
* Explore method to re-dimension the output into user-defined format
* Get an idea of runtime and compute required

https://www.reachhydro.org/home/params/merit-basins

NWM v3.0: https://noaa-nwm-retrospective-3-0-pds.s3.amazonaws.com/index.html

**Comment by samlamont** [comment]
In my tests the weight generation step took about 25 mins, and the MAP calculation took about 11 minutes for one month of NWM v3.0 data and ~200,000 MERIT catchments.  

So for the entire retrospective AORC (40 years) this comes to about 4 days of processing time on this machine (r5.4xlarge EC2 instance: 16 vCPU/128GB memory) , for a single variable (in this case RAINRATE)

**Comment by mgdenno** [comment]
@samlamont this is done correct?

**Comment by samlamont** [comment]
closing as completed
