### ISSUE TITLE
Compare `exactextract` to `generate_weights.py`

### ISSUE THREAD

**Issue by samlamont** [RTIInternational/teehr#125]
### Summary

To summarize grid values to polyons, the Nextgen hydrofabric team uses [exactextract](https://github.com/isciences/exactextract/tree/master).  It calculates the areal fraction of each pixel falling within each polygon, which is similar to the approach in `generate_weights.py`, however it's implemented in C++.

### Goal
Compare the performance and results using `exactextract` vs. `generate_weights.py` for a small test case

**Comment by mgdenno** [comment]
@samlamont this is done correct?

**Comment by samlamont** [comment]
@mgdenno Yes I think this can be considered done, I can close it
