### ISSUE TITLE
Setup benchmarks April 2024

### ISSUE THREAD

**Issue by mgdenno** [RTIInternational/teehr#150]
Here is a list of benchmarks we should setup:

- [ ] 1: TEEHR 1-year parquet files (`usgs_2016.parquet`, `nwm21_2016.parquet`, etc., 9 total) stored locally
- [ ] 2: TEEHR database (`retro.db`) stored locally
- [ ] 3: TEEHR 1-year joined parquet files ('joined_nwm21_retrospective_2016.parquet`, etc.) stored locally
- [ ] 4: TEEHR 1-year parquet files stored in S3
- [ ] 5: TEEHR database stored in S3 (if possible)
- [ ] 6: TEEHR 1-year joined parquet files stored in S3
- [ ] 7: Dask 1-year parquet files (`usgs_2016.parquet`, `nwm21_2016.parquet`, etc., 9 total) stored locally on the `/data` drive
- [ ] 8: Dask database stored locally on the `/data` drive
- [ ] 9: Dask 1-year joined parquet files ('stored locally on the `/data` drive
- [ ] 10: Dask 1-year parquet files stored in S3
- [ ] 11: Dask database stored in S3 (if possible)
- [ ] 12: Dask 1-year joined parquet files stored in S3

For each one we will:
- [ ] Use the 3-yr retrospective dataset
- [ ] Calculate: `root_mean_squared_error`, `relative_bias`, `kling_gupta_efficiency`, `r_squared`, others?
- [ ] Group by `location_id` and `configuration`

What else?

- r5.4xlarge

**Comment by samlamont** [comment]
@mgdenno Looks good, just for clarification, by "Dask database" do you mean Zarr store? 

Also just adding this for reference, have you come across TileDB? https://tiledb.com/open-source/array-storage/

 I originally saw it as a replacement for Zarr but it seems like it has additional functionality.  Maybe we should compile a list of alternatives to research as well (Apache Iceberg, etc)?

**Comment by mgdenno** [comment]
@samlamont A start to this benchmark is here: `data/benchmarks/teehr-benchmark-202404` on TEEHR-HUB.

As far as `Dask database` I copied and pasted that from the ones above so I guess it meant use dask to read the DuckDB database, but that doesn't make sense really.  So, yeah, lets make that one reading from Zarr.

A list of technologies is probably a good idea.  I think I'd split it into `storage` and `compute` layers to start.  In some cases they may be coupled, but not always, and I would likely lean towards solutions where they are not coupled so that we are not locked in to a compute based on storage.

**Comment by mgdenno** [comment]
Done as part of DevCon24 poster
