### ISSUE TITLE
add capability for more than 1 missing flag for USGS and add -999999

### ISSUE THREAD

**Issue by kvanwerkhoven** [RTIInternational/teehr#158]
USGS parquet files contain a large number of values equal to -28316.818359 (-999999 cfs converted to cms).  So seems -999999 must be used as a missing flag in addition to -999.  The one example location I checked reports "ice" on those dates.  Looks like code currently drops data for missing but allows only a single missing flag (-999).  We need to add -999999, and probably other combinations of -9 (-9999, -99999).  Note that negative values are present and real at tidal and backwater locations so we cannot simply remove anything < -999.

**Comment by mgdenno** [comment]
This is fixed in v0.4.0.
