### ISSUE TITLE
Add return class framework to support summaries and visualization

### ISSUE THREAD

**Issue by mgdenno** [RTIInternational/teehr#182]
This will be a significant effort overall but this is the first step towards adding the ability to "post-process" the data that is returned by the queries to generate summaries and to visualize the data.

The current get_xxx() (`e.g., get_metrics()`) methods return a `pd.Dataframe`.  I propose that we make them all return an instance of a new class (e.g., `Metrics()`, etc.) that has a `pd.Dataframe` property, but that we can extend to have other methods such as `.summarize([some args])` and `.plot()` or `.scatter_plot()`.  Alternatively, we could extend the `pd.Dataframe` class, but I am not sure all the implications of that.  It is work investigating. Check this out: https://pandas.pydata.org/docs/development/extending.html#

The first step is to figure out some patterns that will work and implement some basic summarize and plot functionality, then we can move to more complex cases.

**Comment by samlamont** [comment]
Just adding some notes based on some initial exploration.  It seems like pandas [dataframe accessors](https://pandas.pydata.org/docs/reference/api/pandas.api.extensions.register_dataframe_accessor.html#pandas.api.extensions.register_dataframe_accessor) could be an option. 

 We could create a custom [accessor class](https://github.com/RTIInternational/teehr/blob/182-add-return-class-framework-to-support-summaries-and-visualization/src/teehr/classes/dataframe_accessor.py) that contains methods to summarize and plot metrics and/or timeseries, which gets registered as a DataFrame accessor when the class is [imported ](https://github.com/RTIInternational/teehr/blob/b0ab62e5923bd7d3b1315646f92f816bfea318da/src/teehr/classes/duckdb_base.py#L5
).

Then, the queries would still return a DataFrame or GeoDataFrame, but our custom class methods would also be available through the accessor name:

``` python
    df = tds.get_metrics(
        group_by=group_by,
        order_by=order_by,
        include_metrics=include_metrics,
        include_geometry=True,
    )
```
then access our summarize and plot methods like:  `df.teehr.<our custom method>`

for example

```python
    # Call the summarize_metrics method using the teehr accessor.
    summary_df = df.teehr.summarize_metrics(
        group_by=group_by,
        percentiles=[0.25, 0.5, 0.75]
    )
```

Definitely more to think about though!
