### ISSUE TITLE
Python 3.12 / duckdb incompatibility prevents installation of teehr

### ISSUE THREAD

**Issue by jarq6c** [RTIInternational/teehr#188]
Related to https://github.com/duckdb/duckdb/issues/10566

I ran into this issue when trying to install `teehr` locally from github. `pip`/`bdist` will start trying to build the wheel for `duckdb`, spin it's wheels for a long time, then finally choke and error out. I assume this will persist until `duckdb` publishes a release that's compatible with Python 3.12.

You might consider making the python dependency in `pyproject.toml` more strict.

**Comment by mgdenno** [comment]
Thanks for the report.  We have been running/testing on 3.10 and 3.11 and didn't realize that it wouldn't work with 3.12.  We will update the dependency accordingly.

**Comment by mgdenno** [comment]
@samlamont lets catch this in the next release.
