### ISSUE TITLE
Connect the data fetching and data import functionality

### ISSUE THREAD

**Issue by samlamont** [RTIInternational/teehr#221]
- [x] When fetching, read in location IDs from location and/or crosswalk table (issue #211 ) with option to provide list of IDs
- [x] Save fetched data to a manual hive partition scheme (data source/configuration/variable) in the cache (#215)
- [x] Tie together the loading to bring the data from the cache into the dataset
- [x] Create tests for stepping through the locations --> fetch --> load workflow

**Comment by mgdenno** [comment]
I guess one other thing I'd add here (or feel free to create a separate issue if you feel appropriate) would be to confirm/add logging messages.  We should add INFO for general workflow check points and DEBUG with more detailed information.
