### ISSUE TITLE
Consider and discuss changing Evaluation org

### ISSUE THREAD

**Issue by mgdenno** [RTIInternational/teehr#223]
Currently we have and Evaluation class that has "component classes" per "action" type.  For example `load`, `query`, etc.  Should we consider making the "component classes" based on the table name, so instead of `eval.query.timeseries()` it would be `eval.timeseries.query()`.  This would also apply to say getting the filed enum.  That could be property `eval.timeseries.fields` or methodf `eval.timeseries.get_fields()` instead of `eval.fields.timeseries()`.  Also for domain tables, it would be `eval.units.add()`, instead of `eval.load.add_unit()`.  Thoughts @samlamont ?

**Comment by samlamont** [comment]
@mgdenno That sounds good to me! Seems like it provide us (and users) with easy access to the entire dataset schema and, with csv files, would be the "single source of truth", if I understand correctly

**Comment by mgdenno** [comment]
Going to implement changes in https://github.com/RTIInternational/teehr/issues/235
