### ISSUE TITLE
Update docs for v0.4.0

### ISSUE THREAD

**Issue by mgdenno** [RTIInternational/teehr#279]

**Comment by mgdenno** [comment]
See also #281 for new schema diagram.

**Comment by samlamont** [comment]
Not sure where this comment belongs but I'm wondering about our namespace organization for `teehr` imports.  Currently we have an `__init__.py` file in `src/teehr` that imports the `Evaluation` class (and a couple others) so users can just do `from teehr import Evaluation`.

Should we do this for all other classes and models that the user might interact with? 

I guess one approach could be to recommend just `import teehr`, then users could do `teehr.Evaluation()`, or `teehr.Metrics` etc:
* `teehr.Tables`
* `teehr.Bootstrappers`
* `teehr.Operators`
* `teehr.Filters`

Not sure if this makes sense, but it would be good to be consistent throughout the docs and examples

**Comment by mgdenno** [comment]
I agree that we should make it consistent for the user.  I don't know exactly what this looks like, but I think what you've outlined is probably close to what we want.  Lets make a sperate issue to review and refactor namespace and imports

**Comment by mgdenno** [comment]
@samlamont are you planning to review the doc strings for the public API methods as part of this issue?

**Comment by samlamont** [comment]
@mgdenno Yes I can include that here.  The main tasks I think that are needed for the docs are:

- [ ] Updating text and image content of `Getting Started` and `User Guide` pages
- [ ] Updating and including example notebooks 
- [ ] Updating/reviewing imports for consistency (see #286 )
- [ ] Updating/reviewing docstrings

Let me know if you can think of anything I'm missing here

**Comment by mgdenno** [comment]
@samlamont That sounds right.  I think there is probably a bunch of overlap between updating the example notebooks and preparing training materials in #280.  Probably makes sense to let me create the training materials first, so maybe leave that until last.
