### ISSUE TITLE
Fix reference times for analysis_assim_extend data - streamflow and forcing

### ISSUE THREAD

**Issue by kvanwerkhoven** [RTIInternational/teehr#50]
The reference time is 16z for all analysis_assim_extend data.  Currently for streamflow the reference time is 12z in the parquet files and for forcing the reference time is always 1 hour prior to the value time, which is not correct.

**Comment by samlamont** [comment]
Hi @kvanwerkhoven , it seems like we might have a semantics issue with reference time related to assimilation data.  The reference time, which TEEHR reads directly from the file (also named the `model_intialization_time`) for assimilation data is some number of hours prior to the `.tXXz.` time in the file name (depending on the configuration).  The extended assimilation has a 28-hr look back period and is initialized at 12Z every day, with the final simulation hour landing on 16Z of the following day (12Z + 28). So the filenames are each relative to some hour minus 16Z (`.tmXX.`) and the `reference_time` for each file corresponds to the 12Z initialization time.

I was not able to reproduce the issue with the forcing reference time always being 1 hr behind the value time.  It may depend on the values you have specified for `T_MINUS` in TEEHR?

Not sure if this makes sense or helps to explain the issue at all 😄.  Maybe we should be handling reference time for assimilation data differently in TEEHR?  Happy to discuss more if you have any thoughts. 

cc. @mgdenno
