### ISSUE TITLE
USGS loading function not pulling last requested date of range

### ISSUE THREAD

**Issue by kvanwerkhoven** [RTIInternational/teehr#68]
USGS loading function is skipping the last requested day of data.  e.g., the below example pulls data from Aug1-4 but nothing on the 5th.  I tried different dates, period lengths and ending hours and same result every time - the last day does not load though the data exist on NWIS.

tlu.usgs_to_parquet(
    ['02137727'],
    datetime(2023, 8, 1, 0),
    datetime(2023, 8, 5, 23),
    Path('/data/post-event/events/test/timeseries/usgs'),
    chunk_by = 'day'
)

**Comment by samlamont** [comment]
This was addressed in PR #109
