### ISSUE TITLE
Adds NWM v3.0 to loading utils

### ISSUE THREAD

**Issue by mgdenno** [RTIInternational/teehr#73]
NWM 3.0 is live.  Looks like the first v3 outputs in GCP are 9/19 12z. 

We need to add loading utilities for v3.  I suspect that it is largely backwards compatible with our v2.2 code, but I understand there are additional data available that our v2.2 code likely does not allow to be fetched.

**Comment by mgdenno** [comment]
@samlamont I'm trying to track down some documentation that @kvanwerkhoven has describing the changes.

**Comment by samlamont** [comment]
[National Water Model V3.0 SCN .docx](https://github.com/RTIInternational/teehr/files/12701468/National.Water.Model.V3.0.SCN.docx)

yes I saw that in Teams

**Comment by samlamont** [comment]
@mgdenno Looks like  there is now coastal data available (total water level), any thoughts on including this in the loading functions?
