### ISSUE TITLE
Add capability to handle list of pre-built json objects from *remote* store

### ISSUE THREAD

**Issue by jameshalgren** [RTIInternational/teehr#75]
***Goal***
Add feature to permit use of the pre-built json headers for the NWM retrospective and operational archives. This will add a significant speedup to this already zippy library. 

Building the json takes about 30 seconds per file (+/- 50%) and the goal here is to avoid cost of building the json in general. The current script builds the .json and stores it locally. I understand there is (and I would welcome a link to) and issue addressing the ability to use the stored .jsons (instead of rebuilding each time). This issue is similar, except we would be pulling the pre-built .json from a an AWS bucket. 

Below, is a code snippet demonstrating access to those buckets with no download -- this is extremely efficient for one-time access. An alternate method might be to download the .json from the bucket and then to use the workflow as already considered in the above referenced issue. The tradeoff one way or the other is having a location (or not) to store the .json. 

***Explanation***
There are a couple of ways this could be handled. My suggestion is that we begin by permitting two types of input (either a list of strings or list of json objects) at this point in the script --https://github.com/RTIInternational/teehr/blob/0bc0d0eda9cafc0942b8e9b510beb454173c1cc0/src/teehr/loading/nwm22/nwm_grid_data.py#L84

For reference, we have been experimenting with the function of this script using the example notebook here: 
https://github.com/RTIInternational/teehr/blob/main/examples/loading/grid_loading_example.ipynb

The idea would be that the user could choose 
1) to work completely without download (pulling the json objects and data values entirely from buckets (and perhaps even storing the result in an output bucket
2) to work from local cache
  a) with a json object out in the cloud
  b) with a stored json object (downloaded from the cloud or generated)
  c) with a json object generated by this script during the run. (The current default)

***Partial Example***
The following script demonstrates use of fsspec to obtain a series of json objects from the AWS buckets of json headers for the native NWM output. The json objects are then used to open a dataset from the file. This is one way we could access the pre-built files with no download or local storage.
Retrospective output is here: https://ciroh-nwm-zarr-retrospective-data-copy.s3.amazonaws.com/index.html
Operational output (in progress): https://ciroh-nwm-zarr-copy.s3.amazonaws.com/index.html

```
!pip install ujson
!pip install zarr xarray

import joblib
import numpy as np
import xarray as xr
import fsspec
import ujson
import psutil
import concurrent.futures
import multiprocessing

# Get the number of available CPU cores
num_cores = psutil.cpu_count(logical=False)  # Use logical=True for hyperthreading

# Calculate the available memory in GB
available_memory_gb = psutil.virtual_memory().available / (1024 ** 3)  # Bytes to GB

# Calculate a memory limit per worker based on available memory
# Adjust this factor based on your memory usage requirements
memory_per_worker_gb = available_memory_gb / num_cores

# Define a function to load remote JSON content
def load_remote_json(file_url):
    of = fsspec.open(file_url)
    with of as f:
        return ujson.load(f)

# Define a function to load a remote dataset from JSON content
def load_remote_ds(json_obj):
    backend_args = {
        "consolidated": False,
        "storage_options": {
            "fo": json_obj,
        },
    }
    # ON this side, the "fo": points to a json object -- dict type. 
    # on the original script side, "fo" is receiving a string with a file path.
    # We need to modify the library and make a pull request where 
    # we use the loading method in this script with the json object. 
    # The original script assumes there would be a json built at run-time 
    # and stored in a temp/cache directory, so this function only passes
    # the string of the path.
    
    return xr.open_dataset("reference://", engine="zarr", backend_kwargs=backend_args)

# Define a function to select streamflow data from a dataset
def select_flow(ds, feature_id):
    cords = ds.streamflow.sel(feature_id=feature_id)
    return cords.values

# Define a function to process a single file for a given feature ID
def process_file(file_url, feature_ids):
    json_obj = load_remote_json(file_url)
    ds = load_remote_ds(json_obj)
    streamflow_value = select_flow(ds, feature_ids)
    return streamflow_value

# Define a list of feature IDs
feature_ids = [8153461, 8153027, 18210860]
feature_ids = ost

# Define a list of URLs pointing to JSON files
files = []
files.append("https://ciroh-nwm-zarr-copy.s3.amazonaws.com/national-water-model/nwm.20220112/short_range/nwm.t00z.short_range.channel_rt.f001.conus.nc.json")
files.append("https://ciroh-nwm-zarr-copy.s3.amazonaws.com/national-water-model/nwm.20220112/short_range/nwm.t00z.short_range.channel_rt.f002.conus.nc.json")

# Create a dictionary to store the extracted values for each feature ID
extracted_values_dict = {}

# Create a Parallel processing pool using joblib with dynamic settings
with joblib.parallel_backend("threading", n_jobs=num_cores):  # Use threads for parallel processing
    streamflow_values = joblib.Parallel()(joblib.delayed(process_file)(file_url, feature_ids) for file_url in files)

```

@pclemins
@trupeshkumarpatel
@hariteja-jajula 
@samlamont

**Comment by mgdenno** [comment]
https://docs.ciroh.org/docs/products/tools/dataaccess/

**Comment by jameshalgren** [comment]
The lowest hanging fruit here is probably 2b from the list above -- that would require almost 0 refactoring. We would just include an option to download the .json file instead of generating it (and failback to generating if something goes wrong with the download.)

**Comment by mgdenno** [comment]
@jameshalgren, @samlamont is working on addressing this issue this week.
