### ISSUE TITLE
Loading request validation misses some bad parameters

### ISSUE THREAD

**Issue by mgdenno** [RTIInternational/teehr#78]
The `OutputTypesEnum` is used for all data loading requests but all the output types included are not valid for all configurations.  Therefore it does not accurately validate the request as it allows the user to select an output type that is not valid for the configuration they select.

https://github.com/RTIInternational/teehr/blob/0bc0d0eda9cafc0942b8e9b510beb454173c1cc0/src/teehr/loading/nwm22/point_config_models.py#L60

**Comment by samlamont** [comment]
This should be fixed by PR #73 , sorry I should have raised this issue earlier
