### ISSUE TITLE
Remove extraneous fields from NWM2.1 Retrospective

### ISSUE THREAD

**Issue by mgdenno** [RTIInternational/teehr#86]
The NWM2.1 seems to have some additional fields that the NWM2.0 does not haver when saved as parquet.  These can be removed with the following line of code: `df.drop(["elevation", "gage_id", "order"], axis=1, inplace=True)`.  Probably also need to use `errors="ignore"` so it won't fail on NWM2.0 which does not have them.

**Comment by samlamont** [comment]
Addressed in PR #109
